FROM openjdk:11-jre-slim

# Add a volume pointing to /tmp, spring writes to it
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/config-server-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} cs.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dserver.port=8080","-jar","/cs.jar"]

# docker image build -t todarch/cs:latest -f dockerfiles/dockerfile-local .
# docker container run -it --rm --name todarch-cs -p 8081:8080 todarch/cs
# localhost:8081/td/default/master
